input-language C/C++
decl-version 2.0
var-comparability implicit

ppt ..main():::ENTER
  ppt-type enter
  variable ::words2
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::words2[..]
    var-kind array
    enclosing-var ::words2
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::words2mem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 2
  variable ::words2ptrs
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::words2ptrs[..]
    var-kind array
    enclosing-var ::words2ptrs
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::wordss
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::wordss[..]
    var-kind array
    enclosing-var ::wordss
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::keymem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 2
  variable ::wordsn
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 1
  variable ::wordsn[..]
    var-kind array
    enclosing-var ::wordsn
    array 1
    rep-type int[]
    dec-type int[]
    comparability 3
  variable ::wordmasks
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 1
  variable ::wordmasks[..]
    var-kind array
    enclosing-var ::wordmasks
    array 1
    rep-type int[]
    dec-type int[]
    comparability 4
  variable ::ncount
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable ::longestlength
    var-kind variable
    rep-type int
    dec-type int
    comparability 3
  variable ::largestlet
    var-kind variable
    rep-type int
    dec-type char
    comparability 2
  variable ::rec_anag_count
    var-kind variable
    rep-type int
    dec-type int
    comparability 5
  variable ::adjacentdups
    var-kind variable
    rep-type int
    dec-type int
    comparability 6
  variable ::specfirstword
    var-kind variable
    rep-type int
    dec-type int
    comparability 7
  variable ::maxdepthspec
    var-kind variable
    rep-type int
    dec-type int
    comparability 8
  variable ::silent
    var-kind variable
    rep-type int
    dec-type int
    comparability 9
  variable ::max_depth
    var-kind variable
    rep-type int
    dec-type int
    comparability 10
  variable ::vowelcheck
    var-kind variable
    rep-type int
    dec-type int
    comparability 11
  variable ::lindx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx1[..]
    var-kind array
    enclosing-var ::lindx1
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::lindx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx2[..]
    var-kind array
    enclosing-var ::lindx2
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::findx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 12
  variable ::findx1[..]
    var-kind array
    enclosing-var ::findx1
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::findx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 13
  variable ::findx2[..]
    var-kind array
    enclosing-var ::findx2
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable argc
    var-kind variable
    rep-type int
    dec-type int
    flags is_param 
    comparability 14
  variable argv
    var-kind variable
    rep-type hashcode
    dec-type char**
    flags is_param 
    comparability 14
  variable argv[..]
    var-kind array
    enclosing-var argv
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2

ppt ..main():::EXIT0
  ppt-type subexit
  variable ::words2
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::words2[..]
    var-kind array
    enclosing-var ::words2
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::words2mem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 2
  variable ::words2ptrs
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::words2ptrs[..]
    var-kind array
    enclosing-var ::words2ptrs
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::wordss
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::wordss[..]
    var-kind array
    enclosing-var ::wordss
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::keymem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 2
  variable ::wordsn
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 1
  variable ::wordsn[..]
    var-kind array
    enclosing-var ::wordsn
    array 1
    rep-type int[]
    dec-type int[]
    comparability 3
  variable ::wordmasks
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 1
  variable ::wordmasks[..]
    var-kind array
    enclosing-var ::wordmasks
    array 1
    rep-type int[]
    dec-type int[]
    comparability 4
  variable ::ncount
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable ::longestlength
    var-kind variable
    rep-type int
    dec-type int
    comparability 3
  variable ::largestlet
    var-kind variable
    rep-type int
    dec-type char
    comparability 2
  variable ::rec_anag_count
    var-kind variable
    rep-type int
    dec-type int
    comparability 5
  variable ::adjacentdups
    var-kind variable
    rep-type int
    dec-type int
    comparability 6
  variable ::specfirstword
    var-kind variable
    rep-type int
    dec-type int
    comparability 7
  variable ::maxdepthspec
    var-kind variable
    rep-type int
    dec-type int
    comparability 8
  variable ::silent
    var-kind variable
    rep-type int
    dec-type int
    comparability 9
  variable ::max_depth
    var-kind variable
    rep-type int
    dec-type int
    comparability 10
  variable ::vowelcheck
    var-kind variable
    rep-type int
    dec-type int
    comparability 11
  variable ::lindx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx1[..]
    var-kind array
    enclosing-var ::lindx1
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::lindx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx2[..]
    var-kind array
    enclosing-var ::lindx2
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::findx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 12
  variable ::findx1[..]
    var-kind array
    enclosing-var ::findx1
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::findx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 13
  variable ::findx2[..]
    var-kind array
    enclosing-var ::findx2
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable argc
    var-kind variable
    rep-type int
    dec-type int
    flags is_param 
    comparability 14
  variable argv
    var-kind variable
    rep-type hashcode
    dec-type char**
    flags is_param 
    comparability 14
  variable argv[..]
    var-kind array
    enclosing-var argv
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable return
    var-kind variable
    rep-type int
    dec-type int
    comparability 15

ppt ..uppercase():::ENTER
  ppt-type enter
  variable ::upcasestr
    var-kind variable
    reference-type offset
    rep-type string
    dec-type char*
    comparability 1
  variable ::words2
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 2
  variable ::words2[..]
    var-kind array
    enclosing-var ::words2
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 1
  variable ::words2mem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 1
  variable ::words2ptrs
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 2
  variable ::words2ptrs[..]
    var-kind array
    enclosing-var ::words2ptrs
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 1
  variable ::wordss
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 2
  variable ::wordss[..]
    var-kind array
    enclosing-var ::wordss
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 3
  variable ::keymem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 1
  variable ::wordsn
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 2
  variable ::wordsn[..]
    var-kind array
    enclosing-var ::wordsn
    array 1
    rep-type int[]
    dec-type int[]
    comparability 4
  variable ::wordmasks
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 5
  variable ::wordmasks[..]
    var-kind array
    enclosing-var ::wordmasks
    array 1
    rep-type int[]
    dec-type int[]
    comparability 6
  variable ::ncount
    var-kind variable
    rep-type int
    dec-type int
    comparability 2
  variable ::longestlength
    var-kind variable
    rep-type int
    dec-type int
    comparability 4
  variable ::largestlet
    var-kind variable
    rep-type int
    dec-type char
    comparability 7
  variable ::rec_anag_count
    var-kind variable
    rep-type int
    dec-type int
    comparability 8
  variable ::adjacentdups
    var-kind variable
    rep-type int
    dec-type int
    comparability 9
  variable ::specfirstword
    var-kind variable
    rep-type int
    dec-type int
    comparability 10
  variable ::maxdepthspec
    var-kind variable
    rep-type int
    dec-type int
    comparability 11
  variable ::silent
    var-kind variable
    rep-type int
    dec-type int
    comparability 12
  variable ::max_depth
    var-kind variable
    rep-type int
    dec-type int
    comparability 13
  variable ::vowelcheck
    var-kind variable
    rep-type int
    dec-type int
    comparability 14
  variable ::lindx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 15
  variable ::lindx1[..]
    var-kind array
    enclosing-var ::lindx1
    array 1
    rep-type int[]
    dec-type int[]
    comparability 16
  variable ::lindx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 17
  variable ::lindx2[..]
    var-kind array
    enclosing-var ::lindx2
    array 1
    rep-type int[]
    dec-type int[]
    comparability 18
  variable ::findx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 19
  variable ::findx1[..]
    var-kind array
    enclosing-var ::findx1
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 20
  variable ::findx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 21
  variable ::findx2[..]
    var-kind array
    enclosing-var ::findx2
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 22
  variable s
    var-kind variable
    rep-type string
    dec-type char*
    flags is_param 
    comparability 1

ppt ..uppercase():::EXIT0
  ppt-type subexit
  variable ::upcasestr
    var-kind variable
    reference-type offset
    rep-type string
    dec-type char*
    comparability 1
  variable ::words2
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 2
  variable ::words2[..]
    var-kind array
    enclosing-var ::words2
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 1
  variable ::words2mem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 1
  variable ::words2ptrs
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 2
  variable ::words2ptrs[..]
    var-kind array
    enclosing-var ::words2ptrs
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 1
  variable ::wordss
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 2
  variable ::wordss[..]
    var-kind array
    enclosing-var ::wordss
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 3
  variable ::keymem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 1
  variable ::wordsn
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 2
  variable ::wordsn[..]
    var-kind array
    enclosing-var ::wordsn
    array 1
    rep-type int[]
    dec-type int[]
    comparability 4
  variable ::wordmasks
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 5
  variable ::wordmasks[..]
    var-kind array
    enclosing-var ::wordmasks
    array 1
    rep-type int[]
    dec-type int[]
    comparability 6
  variable ::ncount
    var-kind variable
    rep-type int
    dec-type int
    comparability 2
  variable ::longestlength
    var-kind variable
    rep-type int
    dec-type int
    comparability 4
  variable ::largestlet
    var-kind variable
    rep-type int
    dec-type char
    comparability 7
  variable ::rec_anag_count
    var-kind variable
    rep-type int
    dec-type int
    comparability 8
  variable ::adjacentdups
    var-kind variable
    rep-type int
    dec-type int
    comparability 9
  variable ::specfirstword
    var-kind variable
    rep-type int
    dec-type int
    comparability 10
  variable ::maxdepthspec
    var-kind variable
    rep-type int
    dec-type int
    comparability 11
  variable ::silent
    var-kind variable
    rep-type int
    dec-type int
    comparability 12
  variable ::max_depth
    var-kind variable
    rep-type int
    dec-type int
    comparability 13
  variable ::vowelcheck
    var-kind variable
    rep-type int
    dec-type int
    comparability 14
  variable ::lindx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 15
  variable ::lindx1[..]
    var-kind array
    enclosing-var ::lindx1
    array 1
    rep-type int[]
    dec-type int[]
    comparability 16
  variable ::lindx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 17
  variable ::lindx2[..]
    var-kind array
    enclosing-var ::lindx2
    array 1
    rep-type int[]
    dec-type int[]
    comparability 18
  variable ::findx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 19
  variable ::findx1[..]
    var-kind array
    enclosing-var ::findx1
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 20
  variable ::findx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 21
  variable ::findx2[..]
    var-kind array
    enclosing-var ::findx2
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 22
  variable s
    var-kind variable
    rep-type string
    dec-type char*
    flags is_param 
    comparability 1
  variable return
    var-kind variable
    rep-type string
    dec-type char*
    comparability 1

ppt ..alphabetic():::ENTER
  ppt-type enter
  variable ::alphstr
    var-kind variable
    reference-type offset
    rep-type string
    dec-type char*
    comparability 1
  variable ::words2
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 2
  variable ::words2[..]
    var-kind array
    enclosing-var ::words2
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 1
  variable ::words2mem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 1
  variable ::words2ptrs
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 2
  variable ::words2ptrs[..]
    var-kind array
    enclosing-var ::words2ptrs
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 1
  variable ::wordss
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 2
  variable ::wordss[..]
    var-kind array
    enclosing-var ::wordss
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 3
  variable ::keymem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 1
  variable ::wordsn
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 2
  variable ::wordsn[..]
    var-kind array
    enclosing-var ::wordsn
    array 1
    rep-type int[]
    dec-type int[]
    comparability 4
  variable ::wordmasks
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 5
  variable ::wordmasks[..]
    var-kind array
    enclosing-var ::wordmasks
    array 1
    rep-type int[]
    dec-type int[]
    comparability 6
  variable ::ncount
    var-kind variable
    rep-type int
    dec-type int
    comparability 2
  variable ::longestlength
    var-kind variable
    rep-type int
    dec-type int
    comparability 4
  variable ::largestlet
    var-kind variable
    rep-type int
    dec-type char
    comparability 7
  variable ::rec_anag_count
    var-kind variable
    rep-type int
    dec-type int
    comparability 8
  variable ::adjacentdups
    var-kind variable
    rep-type int
    dec-type int
    comparability 9
  variable ::specfirstword
    var-kind variable
    rep-type int
    dec-type int
    comparability 10
  variable ::maxdepthspec
    var-kind variable
    rep-type int
    dec-type int
    comparability 11
  variable ::silent
    var-kind variable
    rep-type int
    dec-type int
    comparability 12
  variable ::max_depth
    var-kind variable
    rep-type int
    dec-type int
    comparability 13
  variable ::vowelcheck
    var-kind variable
    rep-type int
    dec-type int
    comparability 14
  variable ::lindx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 15
  variable ::lindx1[..]
    var-kind array
    enclosing-var ::lindx1
    array 1
    rep-type int[]
    dec-type int[]
    comparability 16
  variable ::lindx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 17
  variable ::lindx2[..]
    var-kind array
    enclosing-var ::lindx2
    array 1
    rep-type int[]
    dec-type int[]
    comparability 18
  variable ::findx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 19
  variable ::findx1[..]
    var-kind array
    enclosing-var ::findx1
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 20
  variable ::findx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 21
  variable ::findx2[..]
    var-kind array
    enclosing-var ::findx2
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 22
  variable s
    var-kind variable
    rep-type string
    dec-type char*
    flags is_param 
    comparability 1

ppt ..alphabetic():::EXIT0
  ppt-type subexit
  variable ::alphstr
    var-kind variable
    reference-type offset
    rep-type string
    dec-type char*
    comparability 1
  variable ::words2
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 2
  variable ::words2[..]
    var-kind array
    enclosing-var ::words2
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 1
  variable ::words2mem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 1
  variable ::words2ptrs
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 2
  variable ::words2ptrs[..]
    var-kind array
    enclosing-var ::words2ptrs
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 1
  variable ::wordss
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 2
  variable ::wordss[..]
    var-kind array
    enclosing-var ::wordss
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 3
  variable ::keymem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 1
  variable ::wordsn
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 2
  variable ::wordsn[..]
    var-kind array
    enclosing-var ::wordsn
    array 1
    rep-type int[]
    dec-type int[]
    comparability 4
  variable ::wordmasks
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 5
  variable ::wordmasks[..]
    var-kind array
    enclosing-var ::wordmasks
    array 1
    rep-type int[]
    dec-type int[]
    comparability 6
  variable ::ncount
    var-kind variable
    rep-type int
    dec-type int
    comparability 2
  variable ::longestlength
    var-kind variable
    rep-type int
    dec-type int
    comparability 4
  variable ::largestlet
    var-kind variable
    rep-type int
    dec-type char
    comparability 7
  variable ::rec_anag_count
    var-kind variable
    rep-type int
    dec-type int
    comparability 8
  variable ::adjacentdups
    var-kind variable
    rep-type int
    dec-type int
    comparability 9
  variable ::specfirstword
    var-kind variable
    rep-type int
    dec-type int
    comparability 10
  variable ::maxdepthspec
    var-kind variable
    rep-type int
    dec-type int
    comparability 11
  variable ::silent
    var-kind variable
    rep-type int
    dec-type int
    comparability 12
  variable ::max_depth
    var-kind variable
    rep-type int
    dec-type int
    comparability 13
  variable ::vowelcheck
    var-kind variable
    rep-type int
    dec-type int
    comparability 14
  variable ::lindx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 15
  variable ::lindx1[..]
    var-kind array
    enclosing-var ::lindx1
    array 1
    rep-type int[]
    dec-type int[]
    comparability 16
  variable ::lindx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 17
  variable ::lindx2[..]
    var-kind array
    enclosing-var ::lindx2
    array 1
    rep-type int[]
    dec-type int[]
    comparability 18
  variable ::findx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 19
  variable ::findx1[..]
    var-kind array
    enclosing-var ::findx1
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 20
  variable ::findx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 21
  variable ::findx2[..]
    var-kind array
    enclosing-var ::findx2
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 22
  variable s
    var-kind variable
    rep-type string
    dec-type char*
    flags is_param 
    comparability 1
  variable return
    var-kind variable
    rep-type string
    dec-type char*
    comparability 1

ppt ..numvowels():::ENTER
  ppt-type enter
  variable ::words2
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::words2[..]
    var-kind array
    enclosing-var ::words2
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::words2mem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 2
  variable ::words2ptrs
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::words2ptrs[..]
    var-kind array
    enclosing-var ::words2ptrs
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::wordss
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::wordss[..]
    var-kind array
    enclosing-var ::wordss
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::keymem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 2
  variable ::wordsn
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 1
  variable ::wordsn[..]
    var-kind array
    enclosing-var ::wordsn
    array 1
    rep-type int[]
    dec-type int[]
    comparability 3
  variable ::wordmasks
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 1
  variable ::wordmasks[..]
    var-kind array
    enclosing-var ::wordmasks
    array 1
    rep-type int[]
    dec-type int[]
    comparability 4
  variable ::ncount
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable ::longestlength
    var-kind variable
    rep-type int
    dec-type int
    comparability 3
  variable ::largestlet
    var-kind variable
    rep-type int
    dec-type char
    comparability 2
  variable ::rec_anag_count
    var-kind variable
    rep-type int
    dec-type int
    comparability 5
  variable ::adjacentdups
    var-kind variable
    rep-type int
    dec-type int
    comparability 6
  variable ::specfirstword
    var-kind variable
    rep-type int
    dec-type int
    comparability 7
  variable ::maxdepthspec
    var-kind variable
    rep-type int
    dec-type int
    comparability 8
  variable ::silent
    var-kind variable
    rep-type int
    dec-type int
    comparability 9
  variable ::max_depth
    var-kind variable
    rep-type int
    dec-type int
    comparability 10
  variable ::vowelcheck
    var-kind variable
    rep-type int
    dec-type int
    comparability 11
  variable ::lindx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx1[..]
    var-kind array
    enclosing-var ::lindx1
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::lindx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx2[..]
    var-kind array
    enclosing-var ::lindx2
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::findx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 12
  variable ::findx1[..]
    var-kind array
    enclosing-var ::findx1
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::findx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 13
  variable ::findx2[..]
    var-kind array
    enclosing-var ::findx2
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable s
    var-kind variable
    rep-type string
    dec-type char*
    flags is_param 
    comparability 2

ppt ..numvowels():::EXIT0
  ppt-type subexit
  variable ::words2
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::words2[..]
    var-kind array
    enclosing-var ::words2
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::words2mem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 2
  variable ::words2ptrs
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::words2ptrs[..]
    var-kind array
    enclosing-var ::words2ptrs
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::wordss
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::wordss[..]
    var-kind array
    enclosing-var ::wordss
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::keymem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 2
  variable ::wordsn
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 1
  variable ::wordsn[..]
    var-kind array
    enclosing-var ::wordsn
    array 1
    rep-type int[]
    dec-type int[]
    comparability 3
  variable ::wordmasks
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 1
  variable ::wordmasks[..]
    var-kind array
    enclosing-var ::wordmasks
    array 1
    rep-type int[]
    dec-type int[]
    comparability 4
  variable ::ncount
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable ::longestlength
    var-kind variable
    rep-type int
    dec-type int
    comparability 3
  variable ::largestlet
    var-kind variable
    rep-type int
    dec-type char
    comparability 2
  variable ::rec_anag_count
    var-kind variable
    rep-type int
    dec-type int
    comparability 5
  variable ::adjacentdups
    var-kind variable
    rep-type int
    dec-type int
    comparability 6
  variable ::specfirstword
    var-kind variable
    rep-type int
    dec-type int
    comparability 7
  variable ::maxdepthspec
    var-kind variable
    rep-type int
    dec-type int
    comparability 8
  variable ::silent
    var-kind variable
    rep-type int
    dec-type int
    comparability 9
  variable ::max_depth
    var-kind variable
    rep-type int
    dec-type int
    comparability 10
  variable ::vowelcheck
    var-kind variable
    rep-type int
    dec-type int
    comparability 11
  variable ::lindx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx1[..]
    var-kind array
    enclosing-var ::lindx1
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::lindx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx2[..]
    var-kind array
    enclosing-var ::lindx2
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::findx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 12
  variable ::findx1[..]
    var-kind array
    enclosing-var ::findx1
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::findx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 13
  variable ::findx2[..]
    var-kind array
    enclosing-var ::findx2
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable s
    var-kind variable
    rep-type string
    dec-type char*
    flags is_param 
    comparability 2
  variable return
    var-kind variable
    rep-type int
    dec-type int
    comparability 14

ppt ..anagramr7():::ENTER
  ppt-type enter
  variable ::words2
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::words2[..]
    var-kind array
    enclosing-var ::words2
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::words2mem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 2
  variable ::words2ptrs
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::words2ptrs[..]
    var-kind array
    enclosing-var ::words2ptrs
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::wordss
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::wordss[..]
    var-kind array
    enclosing-var ::wordss
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::keymem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 2
  variable ::wordsn
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 1
  variable ::wordsn[..]
    var-kind array
    enclosing-var ::wordsn
    array 1
    rep-type int[]
    dec-type int[]
    comparability 3
  variable ::wordmasks
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 1
  variable ::wordmasks[..]
    var-kind array
    enclosing-var ::wordmasks
    array 1
    rep-type int[]
    dec-type int[]
    comparability 4
  variable ::ncount
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable ::longestlength
    var-kind variable
    rep-type int
    dec-type int
    comparability 3
  variable ::largestlet
    var-kind variable
    rep-type int
    dec-type char
    comparability 2
  variable ::rec_anag_count
    var-kind variable
    rep-type int
    dec-type int
    comparability 5
  variable ::adjacentdups
    var-kind variable
    rep-type int
    dec-type int
    comparability 6
  variable ::specfirstword
    var-kind variable
    rep-type int
    dec-type int
    comparability 7
  variable ::maxdepthspec
    var-kind variable
    rep-type int
    dec-type int
    comparability 8
  variable ::silent
    var-kind variable
    rep-type int
    dec-type int
    comparability 9
  variable ::max_depth
    var-kind variable
    rep-type int
    dec-type int
    comparability 10
  variable ::vowelcheck
    var-kind variable
    rep-type int
    dec-type int
    comparability 11
  variable ::lindx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx1[..]
    var-kind array
    enclosing-var ::lindx1
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::lindx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx2[..]
    var-kind array
    enclosing-var ::lindx2
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::findx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 12
  variable ::findx1[..]
    var-kind array
    enclosing-var ::findx1
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::findx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 13
  variable ::findx2[..]
    var-kind array
    enclosing-var ::findx2
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable s
    var-kind variable
    rep-type string
    dec-type char*
    flags is_param 
    comparability 2
  variable accum
    var-kind variable
    rep-type hashcode
    dec-type char**
    flags is_param 
    comparability 10
  variable accum[..]
    var-kind array
    enclosing-var accum
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable minkey
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags is_param 
    comparability 14
  variable minkey[..]
    var-kind array
    enclosing-var minkey
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable level
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags is_param 
    comparability 15
  variable level[..]
    var-kind array
    enclosing-var level
    array 1
    rep-type int[]
    dec-type int[]
    comparability 10

ppt ..anagramr7():::EXIT0
  ppt-type subexit
  variable ::words2
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::words2[..]
    var-kind array
    enclosing-var ::words2
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::words2mem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 2
  variable ::words2ptrs
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::words2ptrs[..]
    var-kind array
    enclosing-var ::words2ptrs
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::wordss
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::wordss[..]
    var-kind array
    enclosing-var ::wordss
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::keymem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 2
  variable ::wordsn
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 1
  variable ::wordsn[..]
    var-kind array
    enclosing-var ::wordsn
    array 1
    rep-type int[]
    dec-type int[]
    comparability 3
  variable ::wordmasks
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 1
  variable ::wordmasks[..]
    var-kind array
    enclosing-var ::wordmasks
    array 1
    rep-type int[]
    dec-type int[]
    comparability 4
  variable ::ncount
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable ::longestlength
    var-kind variable
    rep-type int
    dec-type int
    comparability 3
  variable ::largestlet
    var-kind variable
    rep-type int
    dec-type char
    comparability 2
  variable ::rec_anag_count
    var-kind variable
    rep-type int
    dec-type int
    comparability 5
  variable ::adjacentdups
    var-kind variable
    rep-type int
    dec-type int
    comparability 6
  variable ::specfirstword
    var-kind variable
    rep-type int
    dec-type int
    comparability 7
  variable ::maxdepthspec
    var-kind variable
    rep-type int
    dec-type int
    comparability 8
  variable ::silent
    var-kind variable
    rep-type int
    dec-type int
    comparability 9
  variable ::max_depth
    var-kind variable
    rep-type int
    dec-type int
    comparability 10
  variable ::vowelcheck
    var-kind variable
    rep-type int
    dec-type int
    comparability 11
  variable ::lindx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx1[..]
    var-kind array
    enclosing-var ::lindx1
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::lindx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx2[..]
    var-kind array
    enclosing-var ::lindx2
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::findx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 12
  variable ::findx1[..]
    var-kind array
    enclosing-var ::findx1
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::findx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 13
  variable ::findx2[..]
    var-kind array
    enclosing-var ::findx2
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable s
    var-kind variable
    rep-type string
    dec-type char*
    flags is_param 
    comparability 2
  variable accum
    var-kind variable
    rep-type hashcode
    dec-type char**
    flags is_param 
    comparability 10
  variable accum[..]
    var-kind array
    enclosing-var accum
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable minkey
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags is_param 
    comparability 14
  variable minkey[..]
    var-kind array
    enclosing-var minkey
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable level
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags is_param 
    comparability 15
  variable level[..]
    var-kind array
    enclosing-var level
    array 1
    rep-type int[]
    dec-type int[]
    comparability 10

ppt ..extract():::ENTER
  ppt-type enter
  variable ::r1
    var-kind variable
    reference-type offset
    rep-type string
    dec-type char*
    comparability 1
  variable ::words2
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 2
  variable ::words2[..]
    var-kind array
    enclosing-var ::words2
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 1
  variable ::words2mem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 1
  variable ::words2ptrs
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 2
  variable ::words2ptrs[..]
    var-kind array
    enclosing-var ::words2ptrs
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 1
  variable ::wordss
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 2
  variable ::wordss[..]
    var-kind array
    enclosing-var ::wordss
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 1
  variable ::keymem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 1
  variable ::wordsn
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 2
  variable ::wordsn[..]
    var-kind array
    enclosing-var ::wordsn
    array 1
    rep-type int[]
    dec-type int[]
    comparability 3
  variable ::wordmasks
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 2
  variable ::wordmasks[..]
    var-kind array
    enclosing-var ::wordmasks
    array 1
    rep-type int[]
    dec-type int[]
    comparability 4
  variable ::ncount
    var-kind variable
    rep-type int
    dec-type int
    comparability 2
  variable ::longestlength
    var-kind variable
    rep-type int
    dec-type int
    comparability 3
  variable ::largestlet
    var-kind variable
    rep-type int
    dec-type char
    comparability 1
  variable ::rec_anag_count
    var-kind variable
    rep-type int
    dec-type int
    comparability 5
  variable ::adjacentdups
    var-kind variable
    rep-type int
    dec-type int
    comparability 6
  variable ::specfirstword
    var-kind variable
    rep-type int
    dec-type int
    comparability 7
  variable ::maxdepthspec
    var-kind variable
    rep-type int
    dec-type int
    comparability 8
  variable ::silent
    var-kind variable
    rep-type int
    dec-type int
    comparability 9
  variable ::max_depth
    var-kind variable
    rep-type int
    dec-type int
    comparability 10
  variable ::vowelcheck
    var-kind variable
    rep-type int
    dec-type int
    comparability 11
  variable ::lindx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx1[..]
    var-kind array
    enclosing-var ::lindx1
    array 1
    rep-type int[]
    dec-type int[]
    comparability 2
  variable ::lindx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx2[..]
    var-kind array
    enclosing-var ::lindx2
    array 1
    rep-type int[]
    dec-type int[]
    comparability 2
  variable ::findx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 12
  variable ::findx1[..]
    var-kind array
    enclosing-var ::findx1
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 2
  variable ::findx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 13
  variable ::findx2[..]
    var-kind array
    enclosing-var ::findx2
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 2
  variable s1
    var-kind variable
    rep-type string
    dec-type char*
    flags is_param 
    comparability 1
  variable s2
    var-kind variable
    rep-type string
    dec-type char*
    flags is_param 
    comparability 1

ppt ..extract():::EXIT0
  ppt-type subexit
  variable ::r1
    var-kind variable
    reference-type offset
    rep-type string
    dec-type char*
    comparability 1
  variable ::words2
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 2
  variable ::words2[..]
    var-kind array
    enclosing-var ::words2
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 1
  variable ::words2mem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 1
  variable ::words2ptrs
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 2
  variable ::words2ptrs[..]
    var-kind array
    enclosing-var ::words2ptrs
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 1
  variable ::wordss
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 2
  variable ::wordss[..]
    var-kind array
    enclosing-var ::wordss
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 1
  variable ::keymem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 1
  variable ::wordsn
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 2
  variable ::wordsn[..]
    var-kind array
    enclosing-var ::wordsn
    array 1
    rep-type int[]
    dec-type int[]
    comparability 3
  variable ::wordmasks
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 2
  variable ::wordmasks[..]
    var-kind array
    enclosing-var ::wordmasks
    array 1
    rep-type int[]
    dec-type int[]
    comparability 4
  variable ::ncount
    var-kind variable
    rep-type int
    dec-type int
    comparability 2
  variable ::longestlength
    var-kind variable
    rep-type int
    dec-type int
    comparability 3
  variable ::largestlet
    var-kind variable
    rep-type int
    dec-type char
    comparability 1
  variable ::rec_anag_count
    var-kind variable
    rep-type int
    dec-type int
    comparability 5
  variable ::adjacentdups
    var-kind variable
    rep-type int
    dec-type int
    comparability 6
  variable ::specfirstword
    var-kind variable
    rep-type int
    dec-type int
    comparability 7
  variable ::maxdepthspec
    var-kind variable
    rep-type int
    dec-type int
    comparability 8
  variable ::silent
    var-kind variable
    rep-type int
    dec-type int
    comparability 9
  variable ::max_depth
    var-kind variable
    rep-type int
    dec-type int
    comparability 10
  variable ::vowelcheck
    var-kind variable
    rep-type int
    dec-type int
    comparability 11
  variable ::lindx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx1[..]
    var-kind array
    enclosing-var ::lindx1
    array 1
    rep-type int[]
    dec-type int[]
    comparability 2
  variable ::lindx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx2[..]
    var-kind array
    enclosing-var ::lindx2
    array 1
    rep-type int[]
    dec-type int[]
    comparability 2
  variable ::findx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 12
  variable ::findx1[..]
    var-kind array
    enclosing-var ::findx1
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 2
  variable ::findx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 13
  variable ::findx2[..]
    var-kind array
    enclosing-var ::findx2
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 2
  variable s1
    var-kind variable
    rep-type string
    dec-type char*
    flags is_param 
    comparability 1
  variable s2
    var-kind variable
    rep-type string
    dec-type char*
    flags is_param 
    comparability 1
  variable return
    var-kind variable
    rep-type string
    dec-type char*
    comparability 1

ppt ..intmask():::ENTER
  ppt-type enter
  variable ::words2
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::words2[..]
    var-kind array
    enclosing-var ::words2
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::words2mem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 2
  variable ::words2ptrs
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::words2ptrs[..]
    var-kind array
    enclosing-var ::words2ptrs
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::wordss
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::wordss[..]
    var-kind array
    enclosing-var ::wordss
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::keymem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 2
  variable ::wordsn
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 1
  variable ::wordsn[..]
    var-kind array
    enclosing-var ::wordsn
    array 1
    rep-type int[]
    dec-type int[]
    comparability 3
  variable ::wordmasks
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 1
  variable ::wordmasks[..]
    var-kind array
    enclosing-var ::wordmasks
    array 1
    rep-type int[]
    dec-type int[]
    comparability 4
  variable ::ncount
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable ::longestlength
    var-kind variable
    rep-type int
    dec-type int
    comparability 3
  variable ::largestlet
    var-kind variable
    rep-type int
    dec-type char
    comparability 2
  variable ::rec_anag_count
    var-kind variable
    rep-type int
    dec-type int
    comparability 5
  variable ::adjacentdups
    var-kind variable
    rep-type int
    dec-type int
    comparability 6
  variable ::specfirstword
    var-kind variable
    rep-type int
    dec-type int
    comparability 7
  variable ::maxdepthspec
    var-kind variable
    rep-type int
    dec-type int
    comparability 8
  variable ::silent
    var-kind variable
    rep-type int
    dec-type int
    comparability 9
  variable ::max_depth
    var-kind variable
    rep-type int
    dec-type int
    comparability 10
  variable ::vowelcheck
    var-kind variable
    rep-type int
    dec-type int
    comparability 11
  variable ::lindx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx1[..]
    var-kind array
    enclosing-var ::lindx1
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::lindx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx2[..]
    var-kind array
    enclosing-var ::lindx2
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::findx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 12
  variable ::findx1[..]
    var-kind array
    enclosing-var ::findx1
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::findx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 13
  variable ::findx2[..]
    var-kind array
    enclosing-var ::findx2
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable s
    var-kind variable
    rep-type string
    dec-type char*
    flags is_param 
    comparability 2

ppt ..intmask():::EXIT0
  ppt-type subexit
  variable ::words2
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::words2[..]
    var-kind array
    enclosing-var ::words2
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::words2mem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 2
  variable ::words2ptrs
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::words2ptrs[..]
    var-kind array
    enclosing-var ::words2ptrs
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::wordss
    var-kind variable
    rep-type hashcode
    dec-type char**
    comparability 1
  variable ::wordss[..]
    var-kind array
    enclosing-var ::wordss
    array 1
    rep-type string[]
    dec-type char*[]
    comparability 2
  variable ::keymem
    var-kind variable
    rep-type string
    dec-type char*
    comparability 2
  variable ::wordsn
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 1
  variable ::wordsn[..]
    var-kind array
    enclosing-var ::wordsn
    array 1
    rep-type int[]
    dec-type int[]
    comparability 3
  variable ::wordmasks
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 1
  variable ::wordmasks[..]
    var-kind array
    enclosing-var ::wordmasks
    array 1
    rep-type int[]
    dec-type int[]
    comparability 4
  variable ::ncount
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable ::longestlength
    var-kind variable
    rep-type int
    dec-type int
    comparability 3
  variable ::largestlet
    var-kind variable
    rep-type int
    dec-type char
    comparability 2
  variable ::rec_anag_count
    var-kind variable
    rep-type int
    dec-type int
    comparability 5
  variable ::adjacentdups
    var-kind variable
    rep-type int
    dec-type int
    comparability 6
  variable ::specfirstword
    var-kind variable
    rep-type int
    dec-type int
    comparability 7
  variable ::maxdepthspec
    var-kind variable
    rep-type int
    dec-type int
    comparability 8
  variable ::silent
    var-kind variable
    rep-type int
    dec-type int
    comparability 9
  variable ::max_depth
    var-kind variable
    rep-type int
    dec-type int
    comparability 10
  variable ::vowelcheck
    var-kind variable
    rep-type int
    dec-type int
    comparability 11
  variable ::lindx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx1[..]
    var-kind array
    enclosing-var ::lindx1
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::lindx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    comparability 3
  variable ::lindx2[..]
    var-kind array
    enclosing-var ::lindx2
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::findx1
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 12
  variable ::findx1[..]
    var-kind array
    enclosing-var ::findx1
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable ::findx2
    var-kind variable
    rep-type hashcode
    dec-type int*
    flags non_null 
    comparability 13
  variable ::findx2[..]
    var-kind array
    enclosing-var ::findx2
    reference-type offset
    array 1
    rep-type int[]
    dec-type int[]
    comparability 1
  variable s
    var-kind variable
    rep-type string
    dec-type char*
    flags is_param 
    comparability 2
  variable return
    var-kind variable
    rep-type int
    dec-type int
    comparability 4

